# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treblle < Formula
  desc ""
  homepage "https://github.com/Treblle/treblle-cli"
  version "0.1.7"

  on_macos do
    url "https://github.com/Treblle/treblle-cli/releases/download/0.1.7/treblle-cli_Darwin_all.tar.gz"
    sha256 "8809c835fcc03aa8b4359568780397d98f6e46e5e3bd441fd08c1e2b0aff5470"

    def install
      bin.install "treblle-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Treblle/treblle-cli/releases/download/0.1.7/treblle-cli_Linux_x86_64.tar.gz"
      sha256 "10381139b96824d03f6b07796643de1e96dea9e22e8120bb6776265e3676e48b"

      def install
        bin.install "treblle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Treblle/treblle-cli/releases/download/0.1.7/treblle-cli_Linux_arm64.tar.gz"
      sha256 "53f5aeead007f23b579b88d05e06282ea1f9f3168e0c74a8896834e69a4ccc0f"

      def install
        bin.install "treblle"
      end
    end
  end
end
