# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treblle < Formula
  desc ""
  homepage "https://github.com/Treblle/treblle-cli"
  version "1.0.78"

  on_macos do
    on_intel do
      url "https://github.com/Treblle/treblle-cli/releases/download/v1.0.78/treblle-cli_1.0.78_darwin_amd64.tar.gz"
      sha256 "769957854783595324cec313659eac2dfd94048803888c42c8d959191216e360"

      def install
        bin.install "treblle"
      end
    end
    on_arm do
      url "https://github.com/Treblle/treblle-cli/releases/download/v1.0.78/treblle-cli_1.0.78_darwin_arm64.tar.gz"
      sha256 "d5a888040dc855641ab12da6bd770515b71ed34d01375926c9018ed5e439866e"

      def install
        bin.install "treblle"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Treblle/treblle-cli/releases/download/v1.0.78/treblle-cli_1.0.78_linux_amd64.tar.gz"
        sha256 "81e5b5300f24cec27258f20d0d5a3d5fbc158cadbe77b7181b7ba15543396336"

        def install
          bin.install "treblle"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Treblle/treblle-cli/releases/download/v1.0.78/treblle-cli_1.0.78_linux_arm64.tar.gz"
        sha256 "f3dfe490e8f82e068243e6e846d4e9a64594bb249d890aa686848f8be9c4d450"

        def install
          bin.install "treblle"
        end
      end
    end
  end
end
